version: "3.7"

services:
  art-shop-front:
    # image: node:12-alpine
    image: artshop:latest
    command: sh -c "npm install && npm run start"
    ports:
      - 4200:4200
    working_dir: /front
    volumes:
      - ./front:/front
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    expose:
      - 4200
  
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos


volumes:
  todo-mysql-data: