controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

items:
    path: /items
    controller: App\Controller\MyItemsController::items